### ISSUE TITLE
ICI workflow: Cache is shared between different jobs

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_control_ci#33]
>  > if the jobs are unique for different branches, then this would solve the case from above?
> 
> Not necessarily. Caches from PRs and scheduled builds would still get mixed up. That might be fine in most cases, but might as well lead to strange errors as the one mentioned above.
> 
> I guess, the cleanest would be:
> 
> - Use a proper job identifier (e.g. `github.workflow`)
> - Use three possbile restore keys: 
>   -  `...${{ github.base_ref }}-${{ github.ref }}`
>   - `...${{ github.base_ref }}`
>   - `...${{ github.ref }}`
> 
> This way on a PR it would search for a cache e.g. `...master-my_feature` and if it doesn't find that during the first build use `...master`, while for a scheduled build it would use `...master`, since `...master-` and `...` don't exist.
> 
> That could work, right?
> 
> Changing things to actual actions rather than reusable workflow could be a separate discussion, I think.
> 
> _Originally posted by @fmauch in https://github.com/ros-controls/ros2_control_ci/issues/30#issuecomment-1997049189_
>

**Comment by christophfroehlich** [comment]
Summarizing [tests](https://github.com/ros-controls/ros2_control_ci/actions/runs/8708071137/job/23884577080?pr=49)

```yml
name: Reusable test contexts

on:
  workflow_call:

jobs:
  reusable-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Reusable Github.job ${{ github.job }}"
          echo "Reusable Github.workflow ${{ github.workflow }}"
```
```yml
name: Test contexts

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github.job ${{ github.job }}"
          echo "Github.workflow ${{ github.workflow }}"
  call_reusable_test:
    uses: ./.github/workflows/reusable_test_contexts.yml
```

gives 
```console
| Github.job test
| Github.workflow Test contexts
| Reusable Github.job reusable-test
| Reusable Github.workflow Reusable test contexts
```

--> github.workflow does not help here because we still don't get the name of the calling workflow.
